

# Site settings
title: Logospotter
email: info@logospotter.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A collection of UK University logo reviews.

exclude: [bower_components, Gemfile, Gemfile.lock, less, '*.json', '*.rb', Gruntfile.js, README.md, node_modules ]

baseurl: "" # the subpath of your site, e.g. /blog/
url: http://www.logospotter.co.uk # the base hostname & protocol for your site
twitter_username: logospotter
github_username:  logospotter

permalink: none

# Build settings
markdown: kramdown
